### PR TITLE
Fix scroll issue

### PR DESCRIPTION
**Pull request by Justinterest**
### Purpose

- Fix toc scroll into view affect the page scrolling

### Changes

- remove toc scroll into view 

### Review Instructions

related to [docusarus issue](https://github.com/facebook/docusaurus/pull/6748)

solutions:
1. using `scroll-behavior: smooth`, but will cause the back to top button failed, and safari is not fully supported this css feature, only >= 15.4 can support `scroll-behavior`
2. disabled toc `link.scrollIntoView({block: 'nearest'});`, but there are too many toc items, can not auto scrolling to view

So the second method will much better

### CODE REVIEW

**Comment by Vissidarte-Herman** [comment]
Many thanks! Finally, we put this issue to rest.

@FantasyVR @GaleSeLee Please could you also check on your end. 

Cheers,
Keith

**Comment by Vissidarte-Herman** [comment]
LGTM! It works on my macbook.

**Review by Vissidarte-Herman — APPROVED** [review]

**Review by FantasyVR — APPROVED** [review]
LGTM！ Thanks~

**Comment by GaleSeLee** [comment]
When the `ctrl +` ratio is 100%, I still have problems zooming in using the touchpad. But when the radio is greater than 100%, there is not.

**Review by GaleSeLee — APPROVED** [review]

**Pull request merged**
