### PR TITLE
Bump docusaurus version and fix the search functionality.

### PR DESCRIPTION
**Pull request by rexwangcc**
### Purpose

- Bump docusaurus version and fix several issues.
- See if the migration to new Algolia application could fix the issue that our search box cannot find API contents even if they were indexed by the Algolia Crawler already.

### Changes

- Bump the version of docusaurus and make appropriate changes according to the migration guides.
- Fixed the crawler rules on the new Algolia indexer:

```diff
recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
-           lvl1: "header h1",
+           lvl1: "header h1, section h1",
-           content: "article p, article li, article td:last-child",
+           content: "article p, article li, article td:last-child, dt",
            lvl0: {
              selectors: "",
              defaultValue: "Docs",
            },
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
            lvl5: "article h5, article td:first-child",
            lvl6: "article h6",
          },
          indexHeadings: true,
        });
      },
```

### Review Instructions

- No instructions.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks!

**Comment by Vissidarte-Herman** [comment]
...LGTM!

**Comment by Vissidarte-Herman** [comment]
@rexwangcc Some minor issues shy of perfection...

If I search for the `imwrite` method, I find `imwrite` of different versions. In other words, APIs of earlier versions (master, 0.8.0) appear in the search results. Ideally, only the APIs of the latest version should appear in the search results.

**Comment by rexwangcc** [comment]
> @rexwangcc Some minor issues shy of perfection...
> 
> If I search for the `imwrite` method, I find `imwrite` of different versions. In other words, APIs of earlier versions (master, 0.8.0) appear in the search results. Ideally, only the APIs of the latest version should appear in the search results.

Makes sense, I think what we need here is a facet based on API versions.

**Pull request merged**
